on:
  workflow_dispatch:

jobs:
  terraform-deploy:
    uses: CelineSten/iac-mvp/.github/workflows/terraform-poc.yml@v8
    with:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}