on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'The environment to use'
        type: environment
        required: true

jobs:
  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      ARM_CLIENT_ID: {{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: {{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: {{ vars.ARM_SUBSCRIPTION_ID }}

  manual-approval:
    needs: [terraform-plan]
    runs-on: ubuntu-latest
    environment: manual-approval
    steps:
      - name: Approval
        run: echo "Approved"

  terraform-apply:
    needs: [manual-approval]
    uses: ./.github/workflows/terraform-apply.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      ARM_CLIENT_ID: {{ vars.ARM_CLIENT_ID }}
      ARM_TENANT_ID: {{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: {{ vars.ARM_SUBSCRIPTION_ID }}